Adapting Mautic update to work with our releases

diff --git a/.github/workflows/fa-release.yml b/.github/workflows/fa-release.yml
--- a/.github/workflows/fa-release.yml
+++ b/.github/workflows/fa-release.yml
@@ -22,6 +22,16 @@ jobs:
     - name: Get tag name
       run: echo "MAUTIC_VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
 
+    - name: Check if tag name matches version in release_metadata.json
+      run: |
+        METADATA_VERSION=$(jq -r '.version' app/release_metadata.json)
+        if [[ "${{ env.MAUTIC_VERSION }}" != "$METADATA_VERSION" ]]; then
+          echo "❌ ERROR: tag name (${{ env.MAUTIC_VERSION }}) doesn't match version in app/release_metadata.json ($METADATA_VERSION). Please ensure that both versions match!"
+          exit 1
+        else
+          echo "✔ Tag name (${{ env.MAUTIC_VERSION }}) and the version in app/release_metadata.json ($METADATA_VERSION) match. Great!"
+        fi
+
     - name: Install dependencies
       run: |
         composer validate
@@ -57,8 +67,24 @@ jobs:
         asset_name: ${{ env.MAUTIC_VERSION }}.zip
         asset_content_type: application/zip
 
+   - name: Upload update package ${{ env.MAUTIC_VERSION }}-update.zip
+      uses: actions/upload-release-asset@v1
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        upload_url: ${{ steps.create_release.outputs.upload_url }}
+        asset_path: ./build/packages/${{ env.MAUTIC_VERSION }}-update.zip
+        asset_name: ${{ env.MAUTIC_VERSION }}-update.zip
+        asset_content_type: application/zip
+
     - name: Store full package artifact
       uses: actions/upload-artifact@v2
       with:
         name: ${{ env.MAUTIC_VERSION }}.zip
         path: ./build/packages/${{ env.MAUTIC_VERSION }}.zip
+
+    - name: Store update package artifact
+      uses: actions/upload-artifact@v2
+      with:
+        name: ${{ env.MAUTIC_VERSION }}-update.zip
+        path: ./build/packages/${{ env.MAUTIC_VERSION }}-update.zip
